datastax/pulsar

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchBWCTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java

If the key is null or "" (the previous behaviour of the ES sink with the provided [extractKeyValue](https://github.com/vroyer/pulsar/blob/branch-2.6/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java#L97)),  the doc is indexed with an auto generated random _id. So the default configuration is now keyIgnore=true, and nullValueAction=IGNORE.
Also add tests for null values.

Keep the old behaviour with auto generated elasticsearch _id (draft)

---

pom.xml

Downgrading debezium to the same version as apache.
pulsar's connector uses debezium 1.0.0
luna 2.7 uses 1.0.3 https://debezium.io/releases/1.0/release-notes
I tested (locally):
luna 2.7.2 (debezium 1.0.3) => no confirmed_flush_lsn updates
apache 2.7 snapshot upgraded to debezium 1.0.3 => no confirmed_flush_lsn updates
apache 2.7 snapshot with debezium 1.0.0 => confirmed_flush_lsn updates
Downgraded debezium
- Dependencies (does it add or upgrade a dependency): yes, downgrades a dependency

Fix: Postgres WAL does not truncate / confirmed_flush_lsn dows not change.

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/JsonConverterTests.java

Avoid null fields in Elasticsearch when using the ES Sink.
Add a new config settings stripNulls that remove NullNode from the JsonNode tree before converting it into a string.
Add 2 units tests to check the behaviour with stripNulls=true and stripNulls=false
Enhance the ES-Sink.
Self generated through the fieldDoc annotation.

Add stripNulls setting to avoid null in Elasticsearch documents

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java

Cherry-pick of https://github.com/apache/pulsar/pull/11435 into LS272:
The `ack()` method of the `AbstractKafkaSourceRecord` should be non-blocking. Otherwise there'll be deadlock for pulsar-client-io thread and the main `public/default/debezium-mongodb-source-0` thread. And further blocks the whole debezium connector to work correctly.
1. remove the blocking `future.get()` call from `ack()`
2. move the commit logic into callbacks
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #<xyz>
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz> …

make KafkaSourceRecord ack() async to avoid deadlock (#11435)

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java

Add a config option to the Elasticsearch sink allowing to copy the message key fields into the Elasticsearch _source.
Modification in the ElasticSearchSink.
* Add unit tests in ElasticSearchExtractTests
Because the ES Sink …

Add a copyKeyFields config option to the ES sink

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java

Fix the ES Sink default maxRetries to -1 (in order to avoid sink restart)
Set the default maxRetries=-1
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
- The wire protocol: (yes …

Fix ES Sink default maxRetries

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java

In the Elasticsearch Sink, add index/delete retry before failing the write operation.
non-bulk index/delete elasticsearch documents with retry according to the retry configuration.
* Add unit test for index/delete with retry
(Doc generated with …

ES Sink add non-bulk index/delete with retry

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/OverloadShedder.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java

The heartbeat works by using a special namespace pulsar/CLUSTER/brokerid that is always owned by the broker in the name of the namespace.
Any trial to unload that namespace to "shed the load" is deemed to fail.
Modifications:
- in the OverloadShedder and in the ThresholdShedder we are skipping that namespace, in order to cause problems
Notes:
We are doing the filtering in OverloadShedder and in ThresholdShedder and not in ModularLoadManagerImpl because in ModularLoadManagerImpl it would be too late, as the strategies maybe take into consideration the amount of resources that would be freed by unloading the bundle: we must not take those bundles into consideration.
This patch does not change how we calculate resource usage, it is simply saving the LoadManager to do something that is wrong. …

LoadManager: do not try to shed the load on heartbeat namespace

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

Apache PR: https://github.com/apache/pulsar/pull/14475
Some kafka connectors do not sanitize topic names (or incompletely do) to match what downstream system supports.
It works in kafka in most cases, assuming appropriately named topics. This does not work well with Kafka Connect Adaptor because URI part is getting there.
* Flag to sanitize the topic name (disabled by default) and corresponding functionality.
* test
- added unit test
- verified with specific connector that didn't work without this change
- The rest endpoints: …

KCA: Option to sanitize topic name for the connectors that cannot handle pulsar topic names

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/functions/ConsumerConfig.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSourceConsumerConfig.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java
pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java
pulsar-functions/proto/src/main/proto/Function.proto
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeSpawner.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java

JavaInstanceRunnable does not rethrow exception from the sink thus does not give opportunity to the sink to crash and restart.
https://github.com/datastax/pulsar/blob/190e6504ad6460c46cec36eeb80ed94e3dde409a/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java#L351-L362
Cherry-picked 3 commits (only cd9356a03063653e0097f4b85d6b3546698cc325 is actually needed to fix this but it is based on two others, hard to merge cleanly)
```
Author: Boyang Jerry Peng
Date:   Tue Oct 5 22:20:55 2021 -0700
Allow Pulsar Functions localrun to exit on error (#12278)
Co-authored-by: Jerry Peng
(cherry picked from commit cd9356a03063653e0097f4b85d6b3546698cc325)
Author: Boyang Jerry Peng 
Date:   Tue Aug 10 09:33:45 2021 -0700
Allow Pulsar Functions / Sinks to …
```

LS-481: Elastic Search Sink - Sink infinitely tries to reconnect to ES when ES client is in a fail state and does not restart

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/JsonConverterTests.java

Fixes CBB-19
OSS ES Sink should not convert CQL Logical types because such conversion are use-case dependent.
Remove support for CQL logical types and introduce a new config option **ignoreUnsupportedFields** to silently nullify unsupported fields, or process logical types as known AVRO types.
(If …

[CBB-19] Remove support for CQL logical types

---

pulsar-io/kinesis/pom.xml

```
2022-03-20T23:36:01.998033670Z java.lang.NoClassDefFoundError: org/apache/pulsar/functions/source/RecordWithEncryptionContext
2022-03-20T23:36:01.998037400Z 	at org.apache.pulsar.io.kinesis.Utils.serializeRecordToJson(Utils.java:184) ~[?:?]
2022-03-20T23:36:01.998040768Z 	at org.apache.pulsar.io.kinesis.KinesisSink.createKinesisMessage(KinesisSink.java:282) ~[?:?]
2022-03-20T23:36:01.998043838Z 	at org.apache.pulsar.io.kinesis.KinesisSink.write(KinesisSink.java:134) ~[?:?]
2022-03-20T23:36:01.998062435Z 	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:363) ~[com.datastax.oss-pulsar-functions-instance-2.8.0.1.1.27.jar:2.8.0.1.1.27]
2022-03-20T23:36:01.998065988Z 	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleR …
```

Drop provided scope for the pulsar-functions-instance in kinesis sink

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSslConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/RestClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientSslTests.java

Added option to skip SSL certificate validation
`ssl: {"enabled":true, "disableCertificateValidation": true}`
default value is `false`
This option would resolve such problems like
`unable to find valid certification path to requested target`
but it opens an security hole in the network communication with the elastic instance

[elasticsearch] Option to disable SSL certificate validation

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

Same as https://github.com/apache/pulsar/pull/15025
KCA is confused between two KeyValue classes that we have: `org.apache.pulsar.common.schema.KeyValue` and `org.apache.pulsar.io.core.KeyValue`
`getNativeObject()` returns `common.schema.KeyValue` while the KCA expects `io.core.KeyValue`.
As result, sink fails with `ClassCastException: class org.apache.pulsar.common.schema.KeyValue cannot be cast to class org.apache.pulsar.io.core.KeyValue`
Long term it makes sense to get rid of the `io.core.KeyValue` (in the pulsar-io only) and replace its uses with newer `common.schema.KeyValue` (TBD)
For now I added support for both KeyValue types so the change can be cherry-picked into the older branches easily.
Added unit tests
- Dependencies (does …

[pulsar-io] KCA: handle whatever KeyValue getNativeObject() returns: org.apache.pulsar.io.core.KeyValue or org.apache.pulsar.common.schema.KeyValue

---

pulsar-client-admin-shaded/pom.xml
pulsar-client-shaded/pom.xml

Using the `pulsar-client` dependency
```
java.lang.NoClassDefFoundError: com/scurrilous/circe/checksum/Crc32cIntChecksum
```
Added the circe-checksum dependency in the jar

Include circe-checksum in pulsar-client dependency

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/SchemaedFileStreamSinkTask.java

Support `KeyValue<GenericRecord, GenericRecord>` records in KCA sink.
Snowflake connector failed:
```
[SF_KAFKA_CONNECTOR] Detail: Error parsing SinkRecord of native converter or SinkRecord header
[SF_KAFKA_CONNECTOR] Message: Invalid type for STRUCT: class org.apache.pulsar.client.impl.schema.generic.GenericAvroRecord
at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:291) ~[snowflake-kafka-connector-shaded-0.1.8.jar:?]
at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:259) ~[snowflake-kafka-connector-shaded-0.1.8.jar:?]
at com.snowflake.kafka.connector.records.RecordService.convertToJson(RecordService.java:345) ~[snowflake-kafka-connector-shaded-0.1.8.jar:?]
at …
```

KCA Sink to handle KeyValue<GenericRecord, GenericRecord>

---

jclouds-shaded/pom.xml
jclouds-shaded/src/main/java/org/apache/pulsar/jclouds/ShadedJCloudsUtils.java
pom.xml
tiered-storage/jcloud/pom.xml
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/JCloudBlobStoreProvider.java

Modifications:
- add ApacheHCHttpCommandExecutorServiceModule module
- add jclouds driver based on Apache HTTP Client
- add a new ShadedJCloudsUtils that is needed to workaround some problems with the shading of Guice (AbstractModule class is problematic)
- add system property pulsar.jclouds.use_apache_hc to disable the new driver in case of problems

Tiered Storage: add JClouds HttpClient driver

---

jclouds-shaded/pom.xml
jclouds-shaded/src/main/java/org/apache/pulsar/jclouds/ShadedJCloudsUtils.java

Modifications:
- add support for jclouds-okhttp
- you can enable it with -Dpulsar.jclouds.use_okhttp=true
- disable by default Apache HC based driver (pulsar.jclouds.use_apache_hc is now false by default)

Tiered Storage: add OkHttp based provider for JClouds

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java

Basic implementation of canonical output for the key.
If the key schema is avro or json, we sort the fields alphabetically (and recursively).
Implementation notes:
- For JSON, we have to parse and rewrite the entire JSON
- For avro, in this pull, the implementation efficiency can be improved. At the moment: Avro record -> unordered JSON -> ordered JSON. We can remove the intermediate json

[feat][elasticsearch-sink] Option to output canonical JSON

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/RestClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java

New configuration option `keyHashingAlgorithm` which accepts SHA256 and SHA412 as value, default is null.
If you pick an algo, then the id will be hashed before sending the request to elastic 
(this branch is based on es-sink-canonical-output https://github.com/datastax/pulsar/pull/69 )

[feat][elasticsearch] Add hashed id support

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/JsonConverterTests.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java

```
// Map<String, Object> 
ERROR org.apache.pulsar.io.elasticsearch.ElasticSearchSink - write error:
2022-04-26T12:03:34.776219894Z java.lang.IllegalArgumentException: Error while converting a value of type class java.util.HashMap to a MAP: java.lang.ClassCastException: class org.apache.avro.util.Utf8 cannot be cast to class java.lang.String (org.apache.avro.util.Utf8 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
// List/Set
022-04-26T11:56:51.477776276Z Caused by: java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Array cannot be cast to class [Ljava.lang.Object; (org.apache.avro.generic.GenericData$Array is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap') …
```

[fix][elasticsearch-sink] Handle Avro collections native types (GenericData.Array and Utf8 map keys)

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkRawDataTests.java

[feat][elasticsearch-sink] Option to strip out non printable characters

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java

Checkstyle error while running ` mvn clean install -DskipTests` locally
Removed unused import.

Fix: checkstyle error in KinesisSinkTester. 

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderStats.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderStatsDisable.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerOffloaderStatsImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorCache.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorConfig.java
tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/FileSystemLedgerOffloaderFactory.java
tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java
tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/FileStoreTestBase.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloaderTest.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/JCloudLedgerOffloaderFactory.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedInputStreamImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlockAwareSegmentInputStreamImpl.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderStreamingTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java

Currently, there is no offload metrics for tiered storage, so it is very hard for us to debug the performance issues. For example , we can not find why offload is slow or why read offload is slow. For above reasons. we need to add some offload metrics for monitoring.
Add metrics during offload procedure and read offload data procedure. Including offloadTime, offloadError, offloadRate, readLedgerLatency, writeStoreLatency, writeStoreError, readOffloadIndexLatency, readOffloadDataLatency, readOffloadRate, readOffloadError.
(cherry picked from commit 732049fc6ca1beb046deb43057be2b130736fbca)

Offloader metrics (#13833)

---

pulsar-zookeeper/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperServerAspect.java

High CPU usage on Zookeeper nodes of clusters with large metadata size, caused by `approximateDataSize()` calls for `zookeeper_server_data_size_bytes` metric
Switch to enable `zookeeper_server_data_size_bytes` metric, disable by default. 
Pass `-Dstats_use_actual_size=true` to the JVM to enable.

switch for zookeeper_server_data_size_bytes gauge, disable by default

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/CompactedOutBatchMessageTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicMessageImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java
pulsar-common/src/main/proto/PulsarApi.proto
site2/docs/developing-binary-protocol.md
site2/docs/reference-configuration.md

Cherry-picked 
1. https://github.com/apache/pulsar/pull/11553/
2. https://github.com/apache/pulsar/pull/12404
3. https://github.com/apache/pulsar/pull/13336
Needed for KCA sink

Exposing the broker entry metadata to client

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

With the [latest changes to KCA](https://github.com/datastax/pulsar/commit/625da657cf509e547d934cf3b825786866f0386d) now you get this error if the message is batched:
```
java.lang.ClassCastException: class org.apache.pulsar.client.impl.BatchMessageIdImpl cannot be cast to class org.apache.pulsar.client.impl.MessageIdImpl (org.apache.pulsar.client.impl.BatchMessageIdImpl is in unnamed module of loader java.net.URLClassLoader @2ff4acd0; org.apache.pulsar.client.impl.MessageIdImpl is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @6ff415ad)
at org.apache.pulsar.io.kafka.connect.KafkaConnectSink.getMessageOffset(KafkaConnectSink.java:327) ~[pulsar-io-kafka-connect-adaptor-2.8.3.1.0.13.jar:2.8.3.1.0.13]
at org.apache.pulsar.io.kafka.connect.KafkaConnectSink.toSinkRecor …
```

[fix][connector] KCA: use reflection to get pulsar-client impl classes

---

bin/pulsar-shell
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ConfigShell.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/JCommanderCompleter.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/ConfigStore.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/FileConfigStore.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/package-info.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/ConfigShellTest.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/JCommanderCompleterTest.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java

New concept of `configs`
A config is a key-value object where key is a logical name and the value is a client.conf content.
You can now create many configs in the shell and they will be saved in your home directory ($HOME/.pulsar-shell/configs.json)
there's a `default` config which is the config you're passing to pulsar-shell (with `-c`).
New root command: `config`
- config list: list all configs
- config view <configname>: show config value
- config create (--file|--url|--value) <file/url/base64:xx> <configname>: create a config
- config update (--file|--url|--value) <file/url/base64:xx> <configname>: update a config
- config delete <configname>: delete a config
- config use <configname>: set current config to that config 
The last used config will be used as first config for the new …

Pulsar shell: configs to manage multiple clusters/tenants

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/AdminShell.java

Without this change if you add custom commands you get a NPE.
Because setupCommands is running twice

Pulsar shell: allow custom commands

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java

Add a summary to track the time in the cache. I chose a summary instead of a histogram because we don't have any idea of the expected time in the cache. It's not clear to me how expensive it is to track this data via a Prometheus Summary, so we should verify that before pushing it into any production environment.
Add several other metrics related to the consumer's read path.
This PR does not follow the observable guidelines in the Pulsar project to avoid using the prometheus client directly. At the very least, it will be helpful for testing.
* Add Summary named `pulsar_ml_cache_entry_duration_millis` to the `RangeCache`
* As a minor optimization, I only call `System.nanoTime()` once for all of the duration calculations done in each loop
* Add Summary named …

[enh][managed-ledger] Add experimental prometheus metrics

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java

- Remove the Map for a ledger when we invalidate the ledger
- Give priority to "overlapping reads with something missing on the right" (end the loop eagerly, in my testing I have seen that this is the most common case and "missing on the left" happened only very seldom)

Clean up the ledgers cache in PendingReadsManager

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManagerTest.java

- add tests for PendingReadsManager
- fix a bug in discovering overlapping reads with missing entries at both sides (we were actually finding **fewer** matches than the possible ones, so this patch may improve the efficiency of this feature)

Add tests for PendingReadsManager

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java

Cherry-picks of:
https://github.com/apache/pulsar/pull/17638
```
Author: Lari Hotari <lhotari@users.noreply.github.com>
Date:   Mon Sep 19 05:40:18 2022 +0300
[fix][metadata] Handle session events in separate thread (#17638)
(cherry picked from commit 69f3f7471fa6faf24d4776d65e0509538c105d37)
```
https://github.com/apache/pulsar/pull/17909
```
Author: Penghui Li <penghui@apache.org>
Date:   Sun Oct 2 08:46:09 2022 +0800
[fix][broker] Fix the broker shutdown issue after Zookeeper node crashed (#17909)
(cherry picked from commit e26060a1e15a3488fc93cdff6bb0e95e7ec52fed)
```

Cherry-picks of apache PRs 17909 and 17638

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/OffloadUtils.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-io/jdbc/mariadb/src/main/java/org/apache/pulsar/io/jdbc/MariadbJdbcAutoSchemaSink.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestBaseOffload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestFileSystemOffload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestOffloadDeletionFS.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestS3Offload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestUniversalConfigurations.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarTieredStorageTestSuite.java

(cherry picked from commit 08540329c2c1eec262cb0bf728207025fd59f82b)
Fixes #9962 
Offloaded ledgers can be orphaned on topic deletion. 
This is a redo of https://github.com/apache/pulsar/pull/15914 which conflicted with concurrently merged https://github.com/apache/pulsar/pull/17736 thus resulting in https://github.com/apache/pulsar/pull/17889 .
https://github.com/apache/pulsar/pull/17736 made a decision to not allow managed ledger trimming for the fenced mledgers because in many case fencing indicates a problems that should stop all operations on mledger. At the same time fencing is used before deletion starts, so trimming added to the deletion process cannot proceed.
After discussion with @eolivelli I introduced new state, FencedForDeletion, which acts as Fenced state except for the …

[Fix][Tiered Storage] Eagerly Delete Offloaded Segments On Topic Deletion (#17915)

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelector.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/StickyKeyConsumerSelector.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelectorTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java
pulsar-proxy/pom.xml
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyStuckConnectionTest.java

In Kubernetes upgrades, it's possible to get into a state where a TCP/IP connection seems to be alive on the broker. The connection is orphaned and therefore consuming resources and causing resource conflicts with producers and consumers. 
This PR intends to target the issue with consumers that are using the Key shared subscription type with sticky hash ranges. The prevents the issue of "Range conflict with consumer ..." which happens when the previous connection from the client is still active on the broker while the client is reconnecting on a new connection. 
- make `Dispatch.addConsumer` and `StickyKeyConsumerSelector.addConsumer` asynchronous
- add connectionLivenessCheckTimeoutMillis setting that defaults to 5000ms
- when a conflicting consumer is found, first do an active check …

[improve][broker] Prevent range conflicts with Key Shared sticky consumers when TCP/IP connections get orphaned

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSource.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/ErrRecFileStreamSourceTask.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceErrRecTest.java

Support Kafka sources that use commitRecord() and do not implement commit()
Upstream PR: https://github.com/apache/pulsar/pull/20121
added calls to commitRecord() in ack/fail
*If the box was checked, please highlight the changes*
PR in forked repository:

[fix][io] KCA: handle kafka sources that use commitRecord

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtils.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtilsTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusTextFormatUtil.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchMetrics.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java

Follow up of https://github.com/apache/pulsar/pull/20230 that includes a full replacement method for special characters.
The method is now copied~inspired from the official Prometheus java client exporter (that is not in the pulsar classpath)
https://github.com/prometheus/client_java/blob/db2304d042a8f9373504b167efcfbbea13a9e1cd/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L155C23-L172
- Use the new method to replace the special characters in prometheus label values
- Added a unit test

[fix][monitor] topic/subscription with slash breaks the prometheus format

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java

This PR tests the workflows on 3.1_ds branch and contains the fixes for the failed tests. It includes the following changes - 
- Excludes the Build and license check.
- Fixed incorrect groupId's in run_build_unit.sh script (CI - Unit - Other)
- Cherry picked fix for NarUnpackerTest (CI - Unit - Other)
- Cherry picked fix for StrategicCompactionTest.testDispatcherMaxReadSizeBytes (CI - Unit - Brokers - Client Impl)
- Ignored PulsarSinksTest.testCassandraArchiveSink (CI - System - Pulsar IO)
Summary of the cherry picks for unit tests - 
https://docs.google.com/spreadsheets/d/1D4urpSm1iQ3iY8jr2BZ7iP6FggB4DRGk/edit#gid=386183064

[fix][test] Trigger Workflows on 3.1_ds branch 

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh
conf/broker.conf
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/OffloadedLedgerHandle.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadEvictUnusedLedgersTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixReadTest.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtils.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtilsTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusTextFormatUtil.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchMetrics.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticBulkProcessor.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchAuthTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientSslTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/opensearch/OpenSearchClientSslTests.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java

- e9def481e24488b908945a2c8aa5b10c4b2bb7ee - [improve][offloaders] Automatically evict Offloaded Ledgers from memory (#168)
- 8842be93f10871acef09566018bf1e03f7bf227d - [improve][io] Add ElasticSearch Sink bulk debug logs (#179)
- d4c7108827937b9a54eebe7e53c7a7dd08235c5b - [improve][sink]add metrics to elastic search sink
- 110f2f4b6c8c66ef9ec8328a0bedf7cd695ad7f9 - [fix][monitor] topic/subscription with slash breaks the prometheus format (#187)
- Dependencies (does it …

[improve][build, broker, io, storage] Cherry-pick 2.10_ds improvements onto 3.1_ds (part II)

---

src/owasp-dependency-check-false-positives.xml

- a05abe68b0326d7d86a51d7bf732d9f3c33b0709 - Fix Owasp suppressions (move suppressions from org.apache.pulsar to com.datastax.oss)
- 1d5525181038fe8cb7b43da04c659fbf40bfb8ef - Fix owasp-dependency-check supression file
- The default values of configurations: (yes)
- Anything that affects …

[fix][test] Cherry-pick 2.10_ds Fix owasp-dependency-check

---

.github/workflows/pulsar-ci.yaml
distribution/server/src/assemble/LICENSE.bin.txt

Pass binary license check
- Added unaccounted datastax jars in server/LICENSE
- Enabled license check
- Dependencies (does it add or upgrade a dependency): ( no)
(If this PR contains doc changes)

[fix][test] Enabled binary license check for 3.1_ds 

---

conf/functions_worker.yml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PackageUrlValidator.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourcesImpl.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionActionerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/AbstractFunctionApiResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/AbstractFunctionsResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SinkApiV3ResourceTest.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java

Cherry-picked following commits - 
- https://github.com/apache/pulsar/pull/21031
- https://github.com/apache/pulsar/pull/22184
- https://github.com/apache/pulsar/pull/22163 …

[improve][fn, broker] various fixes

---

build/run_unit_group.sh
buildtools/pom.xml
buildtools/src/main/java/org/apache/pulsar/tests/AnnotationListener.java
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
docker/pulsar/Dockerfile
docker/pulsar/pom.xml
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiMultiBrokersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndWithoutBatchIndexAckTest.java
pulsar-sql/presto-distribution/LICENSE
tests/docker-images/java-test-image/pom.xml

This PR sync all commits apache/branch-3.1 into 3.1_ds. 
I cherry-picked the commits of branch-3.1 from 4th Apr 2024 till 5th Apr 2024
- Cherry-picked commits from branch-3.1
- Fixed import issues
- Dependencies (does it add or upgrade a dependency): (yes)
Check …

[improve][broker] Sync commits from apache/pulsar branch-3.1 into 3.1_ds (2)

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Motivation:
If no consumer is sending acks the ManagerCursor is not performing the "rollover", and this leaves long lived ledgers on the bookies, preventing GC.
Modifications:
Periodically enforce that the ManagedCursor check and rollover the BookKeeper ledger at the configured rollover timeout.

[improve][storage] Periodically rollover Cursor ledgers

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LocalPoliciesResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java

Deleting a namespace sometimes fails and leaves znodes around, especially the "bundle owner" nodes `/namespace/NAMESPACE/xxxxxx `
- ensure that all the children of /namespace/NAMESPACE are deleted, especially the ephemeral nodes for ownership
- ensure that on the code path that handles the deletion of the namespace we make progress, the main fact is about not relying on "cache.exists" before using a "delete": the new code is more pessimistic that goes with "deleteIfExists", handling "NotFound" gracefully
- add more logs about the delete namespace execution path
- delete namespace seems to consistently work
- there are no more spammy logs about errors around the topic policies event reader (changelog_events...)
- in case we see an error we log at which point the procedure was (because we …

[improve][broker]Ensure namespace deletion doesn't fail

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LocalPoliciesResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java

Modifications:
- ensure that all the children of /namespace/NAMESPACE are deleted, especially the ephemeral nodes for ownership
- ensure that on the code path that handles the deletion of the namespace we make progress, the main fact is about not relying on "cache.exists" before using a "delete": the new code is more pessimistic that goes with "deleteIfExists", handling "NotFound" gracefully
- add more logs about the delete namespace execution path

Ensure namespace deletion doesn't fail

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerMetadataUtils.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

This is an alternative implemetation to "Compression".
The idea is that we can persist the Position info, that can be huge, in multiple smaller BK entries.
The format is simple: in case of chunking we write all the entries and then a JSON footer.
During recover we read the footer and the previous N entries.
This patch is the initial part of the work, because we have to handle recovery of the case in which the broker crashes while writing the entries.
In this case we have to scan the ledger backward until we find a well-formed entry or a new "footer"

ManagedCursor: chunk position info

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/PositionInfoUtils.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/PositionInfoUtilsTest.java

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #<xyz>
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz>
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
*If …

PositionInfo Util serialization fix and test

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java

Motivation:
- in some cases ManagedCursorImpl dump the list of individuallyDeletedMessages to ZK and writes a znode bigger than 1MB
- this triggers a connection drop from the ZK server, because of the limit of 1MB messages on the wire protocol
Changes:
- log more
- when generating the list of individuallyDeletedMessages, stop at 1MB - 10KB, this is an hard coded limit, to be made configurable in the future
- do not print `individualDeletedMessages.size()` that is rather expensive
Ideal solutions, not possible in a POC:
- change the ZK client and return an error on the client, preventing the server to receive a big message
- ensure that we never write to ZK the cursor info if it is to big (there are 2 cases)

Prevent ZK connection loss in case of huge cursor status

---

pom.xml
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java

To Upgrade debezium version in 2.10
debezium 1.9.7.Final -> 2.5.4.Final
*(example:)*
- Dependencies (does it add or upgrade a dependency): (yes)
(Please explain …

[improve][io] Upgrade debezium to 2.5.4.Final

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java
pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarClassLoader.java

Reproducer:
- configure one EntryFilter in broker.conf
- create a topic (this in turn creates an `EntryFilterWithClassLoader` instance)
- do not use the EntryFilter (don't consume messages)
- unload the topic (this calls EntryFilterWithClassLoader.close() that calls ClassLoader.close())
- consume data from any topic that uses the entry filter
- CRASH ! because the Classloader is closed and it cannot load any other classes
Mofications:
- make it clear that EntryFilterWithClassLoader is not owning the classloader
- enforce also using the Thread ContextClassloader in EntryFilterWithClassLoader (this is another problem, but it didn't affect the specific usecase reported by the user)
Stacktrace:
```
2024-05-09T13:16:13,145+0000 [broker-topic-workers-OrderedExecutor-0-0] ERROR …
```

[broker] EntryFilters fix NoClassDefFoundError due to closed classloader

---

pom.xml
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumMongoDbContainer.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumMySQLContainer.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumPostgreSqlContainer.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/SourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMongoDbSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMsSqlSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMySqlSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumOracleDbSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumPostgreSqlSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarDebeziumOracleSourceTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarDebeziumSourcesTest.java

Update debezium connectors to use 2.6.1.Final
*(example:)*
- Dependencies (does it add or upgrade a dependency): (yes)
(If this PR contains doc …

[fix][io] Upgrade debezium version to 2.6.1.Final

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/AvgShedder.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/AvgShedderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/StandaloneTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPartitionedTopicExpectedTest.java
pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java
pulsar-broker/src/test/resources/configurations/pulsar_broker_test.conf
pulsar-broker/src/test/resources/configurations/pulsar_broker_test_standalone.conf
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java
pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java

This PR sync all commits from apache/branch-3.0 into 3.1_ds which are not present till 30th June.
- Cherry-picked commits from branch-3.0 which are not present on 3.1_ds till 30th June.
(Please …

[improve][misc] Sync commits from apache into 3.1_ds

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java

Addresses
```
2024-08-23T20:40:42,618+0000 [pulsar-stats-updater-OrderedScheduler-0-0] WARN  org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService - Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: 'org.apache.pulsar.common.util.SimpleTextOutputStream org.apache.pulsar.common.util.SimpleTextOutputStream.write(java.lang.String)'
java.lang.NoSuchMethodError: 'org.apache.pulsar.common.util.SimpleTextOutputStream org.apache.pulsar.common.util.SimpleTextOutputStream.write(java.lang.String)'
at org.apache.pulsar.utils.StatsOutputStream.startObject(StatsOutputStream.java:41) ~[com.datastax.oss-pulsar-broker-3.1.3.1.jar:3.1.3.1]
at …
```

AS-4027: add string write function

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AllowSystemTransactionTopicLookupAuthorizationProvider.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/AuthenticatedTransactionProducerConsumerTest.java

Re-do of 26ef2f8eb29c9702a77ebbff1bf925fceeb4829f and 3fb197169eb02d4b45b25e7fa8f832f80c696f5e with adjustments to 3.x codebase.
Also see https://github.com/apache/pulsar/pull/18718
This change is not in the upstream and likely will not be as per https://lists.apache.org/thread/9wtfnzn6h0glyx5w6w69mmgsokl9xq86

[fix][txn] Enable client without system topics permission to use transactions

---

src/update-datastax-license-version.sh

We used to update the datastax jars licenses manually before releasing the lunastreaming 3.1, like this [commit](https://github.com/datastax/pulsar/commit/23d53f90e202062e747289116542cab274d2937a).
With this fix the licenses will be automatically updated as part of the release process.
Added src/update-datastax-license-version.sh
Related PR: [pulsar-distro fix](https://github.com/riptano/pulsar-distro/pull/118)
Check the box below or label this PR directly (if you have …

[improve][misc] Added update-datastax-license-version.sh to update datastax jar licenses automatically while releasing 3.1
