datastax/pulsar

- pom.xml
- pulsar-io/debezium/core/pom.xml
- pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
- pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaWorkerConfig.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/SourceTester.java
Cherry-picking Debezium upgrade from 2.8_ds
haven't run integration test yest / didn't check if they are enabled on this branch
> Upgrade Debezium to v.1.5.4 (last buildable with Java 8)

- conf/proxy.conf
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerDefinition.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerDefinitions.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerMetadata.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerUtils.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerWithClassLoader.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/protocol/ProtocolHandlers.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/protocol/MockProtocolHandler.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerUtilsTest.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/protocol/ProtocolHandlerWithClassLoaderTest.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/protocol/ProtocolHandlersTest.java
Implementation of PIP-93 in Luna Streaming 2.8
> PIP-93 Pulsar Proxy Protocol Handlers

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientTestFixtures.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ReaderImplTest.java
- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
- pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java
- pulsar-io/core/src/main/java/org/apache/pulsar/io/core/ConnectorContext.java
- pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java
- pulsar-io/debezium/mongodb/src/main/resources/debezium-mongodb-source-config.yaml
- pulsar-io/debezium/mysql/src/main/resources/debezium-mysql-source-config.yaml
- pulsar-io/debezium/postgres/src/main/resources/debezium-postgres-source-config.yaml
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaSinkTaskContext.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaWorkerConfig.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java
- site2/docs/functions-debug.md
- site2/docs/io-debezium-source.md
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMongoDbSourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMySqlSourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumPostgreSqlSourceTester.java
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #<xyz>
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz>
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
*If …
> Group of commit for pulsar connectors

- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/JsonConverterTests.java
- add support for dealing with custom logical types 'cql_varint' and 'cql_decimal'
- add test case for 'cql_duration'
> ElasticSearch Sink: handle cql_varint and cql_decimal logical types

- distribution/server/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/server/src/assemble/NOTICE.bin.txt
- docker/pulsar-all/pom.xml
- pom.xml
- pulsar-broker-shaded/pom.xml
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/DataSketchesOpStatsLogger.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/DataSketchesSummaryLogger.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/LongAdderCounter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/ObserverGauge.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusMetricsProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusStatsLogger.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusTextFormatUtil.java
- pulsar-client-admin-shaded/pom.xml
- pulsar-client-all/pom.xml
- pulsar-client-shaded/pom.xml
- pulsar-functions/instance/pom.xml
- pulsar-functions/localrun-shaded/pom.xml
- pulsar-functions/localrun/pom.xml
- pulsar-functions/proto/pom.xml
- pulsar-sql/presto-distribution/LICENSE
- pulsar-zookeeper-utils/pom.xml
- testmocks/src/main/java/org/apache/bookkeeper/client/BookKeeperTestClient.java
- testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
Cherry-picked commits that upgrade grpc and BK
> Grpc upgrade; BK upgrade for LS 2.7

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java
- pulsar-client/pom.xml
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientTestFixtures.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ReaderImplTest.java
Cherry picked fixes for the stuck consumer/Reader
> 2.7.2 ds consumer stuck

- pulsar-client-admin-shaded/pom.xml
- pulsar-client-shaded/pom.xml
I encountered the following problem when using the pulsar client built from `2.8.0_ds`. It looks like we just need to include the right jars, so that they can be shaded.
I can also just push a commit to the branch, but I wanted the change reviewed before it gets merged.
```
3144 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
at …
```
> Include correct bookkeeper jars in pulsar-client jar

- pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java
- pulsar-client-tools/src/test/java/org/apache/pulsar/client/cli/TestCmdProduce.java
Cherry-picking https://github.com/apache/pulsar/pull/11303 and its pre-req https://github.com/apache/pulsar/pull/11069
Support for KV messages is extremely useful while testing the connectors
> [tools] Pulsar Client: add ability to produce KV messages and pre-req

- distribution/io/src/assemble/io.xml
- pulsar-io/debezium/mssql/pom.xml
- pulsar-io/debezium/mssql/src/main/java/org/apache/pulsar/io/debezium/mssql/DebeziumMsSqlSource.java
- pulsar-io/debezium/mssql/src/main/resources/META-INF/services/pulsar-io.yaml
- pulsar-io/debezium/mssql/src/main/resources/debezium-mssql-source-config.yaml
- site2/docs/io-connectors.md
- site2/docs/io-debezium-source.md
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumMsSqlContainer.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMsSqlSourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarDebeziumSourcesTest.java
(cherry picked from commit 5c28686dfc7fb5e473ecec567d18e65c3055856a)
Resolved conflicts in the doc (.md files)
> Added Debezium Source for MS SQL Server (#12256)

- pulsar-io/kinesis/pom.xml
Cherry-picked https://github.com/apache/pulsar/pull/12246
> fix kinesis connector's dependency issue

- tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
removeBlobs does not work properly. This may be a regression in JCloud 2.4..
> Switch BlobStoreManagedLedgerOffloader to use removeBlob

- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java
Same as https://github.com/apache/pulsar/pull/14916
Some Kafka connectors (e.g. JMS) return null as an offset value because underlying system does not support. 
Handle attempt to set null as a partition offset; set it to message.earliest to avoid NPEs (actual value does not matter AFAICT)
This change added unit tests
NO
Check the box below or label this …
> Kafka Connect Adaptor: handle null offsets from kafka connector

- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
See https://github.com/apache/pulsar/pull/14948
> Kinesis integration tests

- pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/json/JsonConverter.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
Same as https://github.com/datastax/pulsar/pull/75 but for Kinesis Sink connector
> [fix][kinesis-sink] Handle Avro collections native types (GenericData.Array and Utf8 map keys)

- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarSchemaToKafkaSchemaTest.java
(cherry picked from commit f90ef9c6ad88c4f94ce1fcc682bbf3f3189cbf2a)
> fix: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type... (#15598)

- pulsar-zookeeper/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperServerAspect.java
Continuation of https://github.com/datastax/pulsar/pull/86
High CPU usage on Zookeeper nodes of clusters with large metadata size, caused by `zkServer.getZKDatabase().getDataTree().getWatchCount()` calls for `zookeeper_server_watches_count ` metric
Weirdly enough, it only happens on 2 nodes out of 5. 
ZK's
```
public int getWatchCount() {
return dataWatches.size() + childWatches.size();
}
```
can be expensive (at least in 3.5.9)
Disabled all gauges by default.
Pass `-D<gauge name>=true` to the JVM to enable.
> disable all ZK gauges by default to reduce CPU utilization

- bin/pulsar-shell
> Fix license check by adding a blank line after license

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
Modifications:
- look for pending reads with a range that includes the requested range
> [enh][broker] Allow to leverage pending reads with partial coverage

- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TransactionAggregator.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTestUtils.java
- pulsar-broker/src/test/resources/prometheus_metrics_sample.txt
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java
Upstream PR https://github.com/apache/pulsar/pull/17419#pullrequestreview-1094344602 by @michaeljmarshall
> [fix][broker] Remove timestamp from broker metrics

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BookieServiceInfoSerde.java
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java
Upstream PR: https://github.com/apache/pulsar/pull/17762
> Make BookieId work with PulsarRegistrationDriver

- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
* [fix][connector] KCA: use reflection to get pulsar-client impl classes
(cherry picked from commit 7e66e5e5f108041f345ba0ec86e643a29ce2380c)
> [fix][connector] KCA: use reflection to get pulsar-client impl classes (#96)

- pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
- pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
Cherry pick https://github.com/apache/pulsar/pull/19082
> [fix][admin] Keep new inputSpecs when updating sink configs (#19082)

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
This is very likely to happen on k8s while a broker is not "ready"
The problem is that UnknownHostException fails very quickly (probably on the same thread), and the "exceptionally" block is executed before we put the CompletableFuture into the `pool` map, and so the "remove" operation fails
```
pulsar-ls-us-central1-a-cluster-c-broker-3 pulsar-ls-us-central1-a-cluster-c-broker 2023-02-27T20:03:53.485151794+01:00 java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: java.net.UnknownHostException: Failed to resolve 'pulsar-ls-us-central1-a-cluster-c-broker-7.pulsar-ls-us-central1-a-cluster-c-broker.pulsar.svc.cluster.local' after 2 queries 
pulsar-ls-us-central1-a-cluster-c-broker-3 …
```
> [bugfix] Fix race condition that leads to caching failed CompletableFutures in ConnectionPool

- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java
Cherry pick https://github.com/apache/pulsar/pull/17106
> [fix][flaky-test]LedgerOffloaderMetricsTest (#17106)

- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/PulsarSchemaToKafkaSchema.java
- pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
Co-authored-by: Andrey Yegorov <andrey.yegorov@datastax.com>
(cherry picked from commit 03f8b806ec177cdf6a5a82193a3fc82557000989)
> [fix][io] KCA sink: handle null values with KeyValue<Avro,Avro> schema (#19861)

- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchTestBase.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearch7SinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearch8SinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/OpenSearchSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
Cherry-picks upstream apache/pulsar#20671
(cherry picked from commit e97fe5b8ac376ecead0097b184f0f1436fce88e4)
> [improve][test] Disable disk usage threshold & geoip download and enable logging for Elastic Testcontainers

- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DefaultLookupProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/URLRegexLookupProxyHandler.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyStuckConnectionTest.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/URLRegexLookupProxyHandlerTest.java
- 62f86e9fd62e54cc16708086f4ddeafcb2de41c4 - Add support for custom proxy lookup handler (#163)
(If you …
> [improve][proxy] Cherry-pick 2.10_ds improvements onto 3.1_ds (part III)

- pom.xml
- pulsar-io/debezium/core/pom.xml
- pulsar-io/kafka-connect-adaptor/pom.xml
- pulsar-io/kafka/pom.xml
- pulsar-io/solr/pom.xml
This PR is meant to fix the OWASP check for `aerospike-client` & `jose4j`.
- Cherry-picked commits from upstream apache/pulsar.
- Dependencies (does it add or upgrade a dependency): (yes)
Check the box below or label this PR directly (if you have committer …
> [fix][build]Version upgrade for deps `aerospike-client` & `jose4j`

- docker/pulsar-all/Dockerfile
This PR updates selects specific connects for pulsar-all docker image
- Select specific connectors, instead of all
- The default values of configurations: (yes)
Need to …
> [cleanup][build] Select specific connectors for pulsar-all docker image  

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java
- Cherry-picked PR #22305
(If this PR contains doc changes)
> [improve][broker] Auth Improvements

- jclouds-shaded/pom.xml
- pom.xml
Cherry-picked https://github.com/apache/pulsar/pull/22220
*If the box was checked, please highlight the changes*
> [fix][broker] Upgrade jclouds

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
- managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java
- testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
- testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockLedgerHandle.java
Fix a problem that happens when the compressed data is smaller than the original data.
> Compressed cursors fix problem with little buffers

- pom.xml
- There is a new release done for Bookkeeper, we want to use it for pulsar 
- Upgraded BookKeeper version
(If this PR contains doc changes)
> Upgrade Bookkeeper

- pulsar-sql/presto-distribution/LICENSE
- There is a new release done for Bookkeeper, we want to use it for pulsar. This PR is meant for upgrading license for bk jars
- Upgraded BookKeeper version
(If this PR contains doc changes)
> [fix][bk] Fixed bookkeeper license version

- pom.xml
Rocksdb version upgrade to 6.29.4.1
> [fix][deps] Rocksdb version upgrade ls210

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
redo of https://github.com/apache/pulsar/pull/23172 on 2.10
> [fix] DLQ to handle bytes key properly

- conf/broker.conf
- conf/standalone.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedReplicationStats.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/DisabledCreateTopicToRemoteClusterForReplicationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/StandaloneTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStatsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java
- pulsar-broker/src/test/resources/configurations/pulsar_broker_test.conf
- pulsar-broker/src/test/resources/configurations/pulsar_broker_test_standalone.conf
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
This PR sync all commits from apache/branch-3.0 into 3.1_ds which are not present till 30th June.
- Cherry-picked commits from branch-3.0 which are not present on 3.1_ds till 30th June.
(Please …
> [improve][misc] Sync commits from apache into 3.1_ds

- distribution/server/src/assemble/LICENSE.bin.txt
- pulsar-sql/presto-distribution/LICENSE
Fix for jackson license version due to version upgrade in [#313](https://github.com/datastax/pulsar/pull/313)
Updated jackson license versions in LICENSE file
Need to update docs?
> [fix][misc] Fixed jackson license version
